import '../models/event.dart';
import '../models/event_category.dart';
import 'event_repository.dart';

class MockEventRepository implements EventRepository {
  MockEventRepository() : _events = _seed();

  final List<Event> _events;

  @override
  List<Event> fetchEvents() => List<Event>.unmodifiable(_events);

  static DateTime _nextWeekday(int weekday, {int hour = 18, int minute = 0}) {
    final DateTime now = DateTime.now();
    final int diff = (weekday - now.weekday + 7) % 7;
    final int daysToAdd = diff == 0 ? 7 : diff;
    final DateTime day = DateTime(now.year, now.month, now.day + daysToAdd);
    return DateTime(day.year, day.month, day.day, hour, minute);
  }

  static const List<String> _avatars = <String>[
    'https://i.pravatar.cc/150?img=12',
    'https://i.pravatar.cc/150?img=25',
    'https://i.pravatar.cc/150?img=33',
    'https://i.pravatar.cc/150?img=41',
    'https://i.pravatar.cc/150?img=5',
    'https://i.pravatar.cc/150?img=8',
    'https://i.pravatar.cc/150?img=19',
    'https://i.pravatar.cc/150?img=22',
    'https://i.pravatar.cc/150?img=29',
    'https://i.pravatar.cc/150?img=36',
    'https://i.pravatar.cc/150?img=44',
    'https://i.pravatar.cc/150?img=27',
    'https://i.pravatar.cc/150?img=38',
    'https://i.pravatar.cc/150?img=49',
  ];

  static List<String> _sampleAvatars(int seed, int n) {
    return List<String>.generate(n, (int i) => _avatars[(seed + i) % _avatars.length]);
  }

  static List<Event> _seed() {
    return <Event>[
      Event(
        id: 'evt-1',
        title: 'Sunday Art Jam — Paint, Sip & Chill',
        coverImageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
        category: EventCategory.art,
        genderPolicy: EventGenderPolicy.womenOnly,
        hostId: 'host-meera',
        hostName: 'Meera S.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=47',
        hostVerified: true,
        hostBio: 'Painter and creative host. Loves calm afternoons and messy palettes.',
        hostEventsHosted: 8,
        hostRating: 4.9,
        startTime: _nextWeekday(DateTime.saturday, hour: 16),
        durationMinutes: 150,
        venueName: 'The Hive',
        venueAddress: '39, 1st A Main Rd, 5th Block, Koramangala, Bengaluru 560034',
        neighbourhood: 'Koramangala',
        priceRupees: 349,
        totalSpots: 20,
        maleRsvpCount: 0,
        femaleRsvpCount: 14,
        attendeeAvatarUrls: _sampleAvatars(0, 6),
        description:
            "Bring your creative energy — we're painting on canvas with acrylics, paired with good coffee and better conversations. No experience needed. Materials provided. Just show up and let the art happen. Wear something you don't mind getting paint on.",
      ),
      Event(
        id: 'evt-2',
        title: 'Beer & Board Games Night',
        coverImageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800',
        category: EventCategory.boardGames,
        hostId: 'host-arjun',
        hostName: 'Arjun K.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=14',
        hostVerified: true,
        hostBio: 'Board game hoarder, pub quiz enthusiast, hosts weekly game nights.',
        hostEventsHosted: 12,
        hostRating: 4.7,
        startTime: _nextWeekday(DateTime.friday, hour: 19),
        durationMinutes: 180,
        venueName: 'Toit Brewpub',
        venueAddress: '298, 100 Feet Rd, Indiranagar, Bengaluru 560038',
        neighbourhood: 'Indiranagar',
        priceRupees: 0,
        totalSpots: 24,
        maleRsvpCount: 9,
        femaleRsvpCount: 9,
        attendeeAvatarUrls: _sampleAvatars(2, 6),
        description:
            "Settlers of Catan, Codenames, Wavelength, Exploding Kittens — I'm bringing 15+ games. Teams randomized so you meet new people. No awkward standing around; you'll be trash-talking strangers within 10 minutes. All skill levels welcome.",
      ),
      Event(
        id: 'evt-3',
        title: 'Sunrise Yoga at Cubbon Park',
        coverImageUrl: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800',
        category: EventCategory.wellness,
        hostId: 'host-riya',
        hostName: 'Riya M.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=45',
        hostVerified: true,
        hostBio: 'Certified instructor, slow flow specialist, morning person.',
        hostEventsHosted: 5,
        hostRating: 4.8,
        startTime: _nextWeekday(DateTime.sunday, hour: 6),
        durationMinutes: 90,
        venueName: 'Cubbon Park',
        venueAddress: 'Band Stand Area, Kasturba Road, Cubbon Park, Bengaluru 560001',
        neighbourhood: 'Cubbon Park',
        priceRupees: 0,
        totalSpots: 30,
        maleRsvpCount: 9,
        femaleRsvpCount: 13,
        attendeeAvatarUrls: _sampleAvatars(3, 6),
        description:
            "Morning yoga in the park, surrounded by trees instead of screens. Bring your own mat or we have a few extras. Post-session filter coffee from the nearby stall. All levels — if you can breathe, you can do this.",
      ),
      Event(
        id: 'evt-4',
        title: 'Badminton Doubles — HSR Courts',
        coverImageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
        category: EventCategory.sports,
        hostId: 'host-vikram',
        hostName: 'Vikram D.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=13',
        hostVerified: true,
        hostBio: 'Weekend player. Believes doubles is the most fun format.',
        hostEventsHosted: 3,
        hostRating: 4.6,
        startTime: _nextWeekday(DateTime.saturday, hour: 7),
        durationMinutes: 120,
        venueName: 'Shuttle Zone',
        venueAddress: 'Sector 2, HSR Layout, Bengaluru 560102',
        neighbourhood: 'HSR Layout',
        priceRupees: 199,
        totalSpots: 16,
        maleRsvpCount: 6,
        femaleRsvpCount: 4,
        attendeeAvatarUrls: _sampleAvatars(4, 6),
        description:
            "Doubles matches with randomized partners. All skill levels — we're here to play, not compete for Olympics. 4 courts booked for 2 hours. Rackets available if you don't have one.",
      ),
      Event(
        id: 'evt-5',
        title: "Women's Book Club — September Pick",
        coverImageUrl: 'https://images.unsplash.com/photo-1521056787327-165eefc12a2e?w=800',
        category: EventCategory.art,
        genderPolicy: EventGenderPolicy.womenOnly,
        hostId: 'host-ananya',
        hostName: 'Ananya R.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=48',
        hostVerified: true,
        hostBio: 'Reader, quiet-cafe hunter, occasional writer.',
        hostEventsHosted: 6,
        hostRating: 5.0,
        startTime: _nextWeekday(DateTime.sunday, hour: 11),
        durationMinutes: 120,
        venueName: 'Atta Galatta',
        venueAddress: '134, KHB Colony, 5th Block, Koramangala, Bengaluru 560034',
        neighbourhood: 'Koramangala',
        priceRupees: 149,
        totalSpots: 12,
        maleRsvpCount: 0,
        femaleRsvpCount: 9,
        attendeeAvatarUrls: _sampleAvatars(5, 6),
        description:
            "This month we're reading 'Shuggie Bain' by Douglas Stuart. Come even if you haven't finished it — no spoiler police here. We'll discuss, argue, recommend, and drink too much coffee. If you're looking for a judgment-free reading community, this is it.",
      ),
      Event(
        id: 'evt-6',
        title: 'Pottery & Clay — Make Your Own Mug',
        coverImageUrl: 'https://images.unsplash.com/photo-1565193286369-a75c4ea24ef7?w=800',
        category: EventCategory.art,
        hostId: 'host-meera',
        hostName: 'Meera S.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=47',
        hostVerified: true,
        hostBio: 'Painter and creative host. Loves calm afternoons and messy palettes.',
        hostEventsHosted: 8,
        hostRating: 4.9,
        startTime: _nextWeekday(DateTime.saturday, hour: 15),
        durationMinutes: 150,
        venueName: 'Claystation Studio',
        venueAddress: '12th Main, HAL 2nd Stage, Indiranagar, Bengaluru 560038',
        neighbourhood: 'Indiranagar',
        priceRupees: 499,
        totalSpots: 16,
        maleRsvpCount: 6,
        femaleRsvpCount: 8,
        attendeeAvatarUrls: _sampleAvatars(6, 6),
        description:
            "Hands in clay, phone in pocket. We're making mugs from scratch — wedging, centering, pulling. Your mug gets fired and you pick it up in a week. Zero experience needed; the studio instructor guides every step.",
      ),
      Event(
        id: 'evt-7',
        title: 'Friday Night Pub Quiz',
        coverImageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
        category: EventCategory.boardGames,
        hostId: 'host-arjun',
        hostName: 'Arjun K.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=14',
        hostVerified: true,
        hostBio: 'Board game hoarder, pub quiz enthusiast, hosts weekly game nights.',
        hostEventsHosted: 12,
        hostRating: 4.7,
        startTime: _nextWeekday(DateTime.friday, hour: 19, minute: 30),
        durationMinutes: 150,
        venueName: 'The Humming Tree',
        venueAddress: '12th Main, HAL 2nd Stage, Indiranagar, Bengaluru 560008',
        neighbourhood: 'Indiranagar',
        priceRupees: 0,
        totalSpots: 30,
        maleRsvpCount: 12,
        femaleRsvpCount: 12,
        attendeeAvatarUrls: _sampleAvatars(7, 6),
        description:
            "5 rounds. Pop culture, sports, Bangalore trivia, science, and a mystery round. Teams of 4-5, randomized so you can't hide behind your smart friend. Winning team gets bragging rights and absolutely nothing else.",
      ),
      Event(
        id: 'evt-8',
        title: 'Agara Lake Sunset Walk',
        coverImageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800',
        category: EventCategory.outdoors,
        hostId: 'host-sneha',
        hostName: 'Sneha P.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=32',
        hostVerified: true,
        hostBio: 'New host. Loves walking-and-talking as a social format.',
        hostEventsHosted: 2,
        hostRating: 4.5,
        startTime: _nextWeekday(DateTime.saturday, hour: 17),
        durationMinutes: 90,
        venueName: 'Agara Lake',
        venueAddress: 'Agara Lake Walking Path, HSR Layout, Bengaluru 560102',
        neighbourhood: 'HSR Layout',
        priceRupees: 0,
        totalSpots: 20,
        maleRsvpCount: 3,
        femaleRsvpCount: 5,
        attendeeAvatarUrls: _sampleAvatars(8, 6),
        description:
            "Walk, talk, breathe. We meet at the main entrance, walk the loop together, and grab chai at the end. No agenda, no icebreaker games — just walking side by side, which is honestly the best way to have a real conversation.",
      ),
      Event(
        id: 'evt-9',
        title: "Women's Cooking Night — South Indian Thali",
        coverImageUrl: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=800',
        category: EventCategory.foodAndDrinks,
        genderPolicy: EventGenderPolicy.womenOnly,
        hostId: 'host-divya',
        hostName: 'Divya N.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=44',
        hostVerified: true,
        hostBio: 'Home cook. Believes filter coffee is a personality trait.',
        hostEventsHosted: 4,
        hostRating: 4.8,
        startTime: _nextWeekday(DateTime.sunday, hour: 17),
        durationMinutes: 180,
        venueName: "Divya's Home Kitchen",
        venueAddress: 'Address shared with confirmed attendees',
        neighbourhood: 'Jayanagar',
        priceRupees: 399,
        totalSpots: 10,
        maleRsvpCount: 0,
        femaleRsvpCount: 8,
        attendeeAvatarUrls: _sampleAvatars(9, 6),
        description:
            "We're making a full thali from scratch — sambar, rasam, poriyal, rice, papad, and payasam. Divide and conquer style. You'll leave knowing how to make at least 3 dishes you've been ordering on Swiggy. Aprons provided.",
      ),
      Event(
        id: 'evt-10',
        title: 'Indie Music Listening Session',
        coverImageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
        category: EventCategory.music,
        hostId: 'host-karthik',
        hostName: 'Karthik V.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=60',
        hostVerified: true,
        hostBio: 'Vinyl collector. Runs a small listening room on the side.',
        hostEventsHosted: 7,
        hostRating: 4.6,
        startTime: _nextWeekday(DateTime.saturday, hour: 18),
        durationMinutes: 150,
        venueName: 'Fandom at Gilly’s',
        venueAddress: '413, 100 Feet Rd, 4th Block, Koramangala, Bengaluru 560034',
        neighbourhood: 'Koramangala',
        priceRupees: 199,
        totalSpots: 25,
        maleRsvpCount: 9,
        femaleRsvpCount: 10,
        attendeeAvatarUrls: _sampleAvatars(10, 6),
        description:
            "Each person brings one song that changed their life. We listen together, the person explains why it matters, we discuss. No mainstream Bollywood; indie, folk, electronic, hip-hop, classical — anything that genuinely moved you. BYO headphones for one segment.",
      ),
      Event(
        id: 'evt-11',
        title: 'Climbing & Bouldering for Beginners',
        coverImageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800',
        category: EventCategory.sports,
        hostId: 'host-priya',
        hostName: 'Priya L.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=32',
        hostVerified: true,
        hostBio: 'Climber. Loves the moment before you commit to a hold.',
        hostEventsHosted: 3,
        hostRating: 4.7,
        startTime: _nextWeekday(DateTime.sunday, hour: 10),
        durationMinutes: 120,
        venueName: 'Boulder Box',
        venueAddress: '3rd Cross, 6th Main, HAL 2nd Stage, Indiranagar, Bengaluru 560038',
        neighbourhood: 'Indiranagar',
        priceRupees: 349,
        totalSpots: 14,
        maleRsvpCount: 3,
        femaleRsvpCount: 3,
        attendeeAvatarUrls: _sampleAvatars(11, 6),
        description:
            "Never climbed before? Perfect — this is literally for you. The gym instructor takes us through safety, basic technique, and then we climb. Something about being 3 meters off the ground makes people actually talk to each other.",
      ),
      Event(
        id: 'evt-12',
        title: 'Late Night Chaai & Deep Conversations',
        coverImageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=800',
        category: EventCategory.foodAndDrinks,
        hostId: 'host-rohit',
        hostName: 'Rohit S.',
        hostPhotoUrl: 'https://i.pravatar.cc/150?img=52',
        hostVerified: true,
        hostBio: 'Question collector. Believes chai + strangers = magic.',
        hostEventsHosted: 5,
        hostRating: 4.9,
        startTime: _nextWeekday(DateTime.friday, hour: 21),
        durationMinutes: 120,
        venueName: 'Third Wave Coffee',
        venueAddress: '27th Main Rd, 1st Sector, HSR Layout, Bengaluru 560102',
        neighbourhood: 'HSR Layout',
        priceRupees: 0,
        totalSpots: 15,
        maleRsvpCount: 5,
        femaleRsvpCount: 7,
        attendeeAvatarUrls: _sampleAvatars(12, 6),
        description:
            "No icebreakers. No networking. Just a table, chai, and a conversation starter deck I made — 50 questions ranging from 'what's a hill you'll die on' to 'what would your 15-year-old self think of you now.' Small group, real talk.",
      ),
    ];
  }
}
