import 'package:flutter/material.dart';
import 'chip_option.dart';

const List<ChipOption> activityOptions = <ChipOption>[
  ChipOption('Breakfast', icon: Icons.free_breakfast_outlined),
  ChipOption('Brunch', icon: Icons.brunch_dining_outlined),
  ChipOption('Lunch', icon: Icons.lunch_dining_outlined),
  ChipOption('Dinner', icon: Icons.dinner_dining_outlined),
  ChipOption('Coffee', icon: Icons.coffee_outlined),
  ChipOption('Picnic', icon: Icons.grass_outlined),
  ChipOption('Barbecue', icon: Icons.outdoor_grill_outlined),
  ChipOption('Board Games', icon: Icons.casino_outlined),
  ChipOption('House Party', icon: Icons.home_outlined),
  ChipOption('Potluck', icon: Icons.ramen_dining_outlined),
  ChipOption('Bike Ride', icon: Icons.directions_bike_outlined),
  ChipOption('Movie', icon: Icons.movie_outlined),
  ChipOption('Road Trip', icon: Icons.directions_car_outlined),
  ChipOption('Karaoke', icon: Icons.mic_outlined),
  ChipOption('Outdoor Event', icon: Icons.terrain_outlined),
  ChipOption('Concert', icon: Icons.stadium_outlined),
  ChipOption('Party', icon: Icons.nightlife_outlined),
  ChipOption('Live Music', icon: Icons.graphic_eq_outlined),
  ChipOption('Art & Craft', icon: Icons.palette_outlined),
  ChipOption('Volunteer', icon: Icons.volunteer_activism_outlined),
  ChipOption('Cooking', icon: Icons.soup_kitchen_outlined),
  ChipOption('Health & Fitness', icon: Icons.fitness_center_outlined),
  ChipOption('Themed Party', icon: Icons.theater_comedy_outlined),
  ChipOption('Book Reading', icon: Icons.menu_book_outlined),
  ChipOption('Gaming', icon: Icons.sports_esports_outlined),
  ChipOption('Shopping', icon: Icons.shopping_bag_outlined),
  ChipOption('Nature Walking', icon: Icons.hiking_outlined),
  ChipOption('Standup Comedy', icon: Icons.record_voice_over_outlined),
  ChipOption('Sightseeing', icon: Icons.photo_camera_outlined),
  ChipOption('Pet Meetup', icon: Icons.pets_outlined),
  ChipOption('Camping', icon: Icons.cabin_outlined),
  ChipOption('Sports', icon: Icons.sports_basketball_outlined),
  ChipOption('Workshops', icon: Icons.build_outlined),
];

const List<ChipOption> traitOptions = <ChipOption>[
  ChipOption('Analytical'),
  ChipOption('Supportive'),
  ChipOption('Proactive'),
  ChipOption('Sociable'),
  ChipOption('Responsible'),
  ChipOption('Tolerant'),
  ChipOption('Punctual'),
  ChipOption('Empathetic'),
  ChipOption('Independent'),
  ChipOption('Leader'),
  ChipOption('Curious'),
  ChipOption('Motivated'),
  ChipOption('Wise'),
  ChipOption('Adaptable'),
  ChipOption('Friendly'),
  ChipOption('Kind'),
  ChipOption('Adventure'),
  ChipOption('Disciplined'),
  ChipOption('Sensitive'),
  ChipOption('Humility'),
  ChipOption('Approachable'),
  ChipOption('Resilient'),
  ChipOption('Confident'),
  ChipOption('Courteous'),
  ChipOption('Cheerful'),
  ChipOption('Practical'),
  ChipOption('Patient'),
  ChipOption('Stubborn'),
  ChipOption('Grateful'),
  ChipOption('Resourceful'),
  ChipOption('Charismatic'),
  ChipOption('Generous'),
  ChipOption('Diligent'),
  ChipOption('Knowledgeable'),
  ChipOption('Openness'),
  ChipOption('Talkative'),
  ChipOption('Organised'),
];

const int maxActivitySelection = 3;
const int maxTraitSelection = 3;
